#!/bin/bash
set -e

NAME=embystat
DEFAULT_FILE=/etc/default/${NAME}

# Source EmbyStat default configuration
if [[ -f $DEFAULT_FILE ]]; then
  . $DEFAULT_FILE
fi

# Data directories for program data (cache, db), configs, and logs
PROGRAMDATA=${EMBYSTAT_DATA_DIRECTORY-/var/lib/$NAME}
CONFIGDATA=${EMBYSTAT_CONFIG_DIRECTORY-/etc/$NAME}
LOGDATA=${EMBYSTAT_LOG_DIRECTORY-/var/log/$NAME}

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [[ -d /run/systemd/system ]] ; then
  systemctl --system daemon-reload >/dev/null || true
fi

case "$1" in
  install|upgrade)
    # try graceful termination;
    if [[ -d /run/systemd/system ]]; then
      deb-systemd-invoke stop ${NAME}.service > /dev/null 2>&1 || true
    elif [ -x "/etc/init.d/${NAME}" ] || [ -e "/etc/init/${NAME}.conf" ]; then
      invoke-rc.d ${NAME} stop > /dev/null 2>&1 || true
    fi
    # try and figure out if embystat is running
    PIDFILE=$(find /var/run/ -maxdepth 1 -mindepth 1  -name "embystat*.pid" -print -quit)
    [[ -n "$PIDFILE" ]] && [[ -s "$PIDFILE" ]] && EMBYSTAT_PID=$(cat ${PIDFILE})
    # if its running, let's stop it
    if [[ -n "$EMBYSTAT_PID" ]]; then
      echo "Stopping EmbyStat!"
      # if embystat is still running, kill it
      if [[ -n "$(ps -p $EMBYSTAT_PID -o pid=)" ]]; then
        CPIDS=$(pgrep -P $EMBYSTAT_PID)
        sleep 2 && kill -KILL $CPIDS
        kill -TERM $CPIDS > /dev/null 2>&1
      fi
      sleep 1
      # if it's still running, show error
      if [[ -n "$(ps -p $EMBYSTAT_PID -o pid=)" ]]; then
        echo "Could not successfully stop EmbyStat Server, please do so before uninstalling."
        exit 1
      else
        [[ -f $PIDFILE ]] && rm $PIDFILE
      fi
    fi

    # If we have existing config or log dirs in /var/lib/embystat, move them into the right place
    if [[ -d $PROGRAMDATA/config ]]; then
        mv $PROGRAMDATA/config $CONFIGDATA
    fi
    if [[ -d $PROGRAMDATA/logs ]]; then
        mv $PROGRAMDATA/logs $LOGDATA
    fi

    ;;
  abort-upgrade)
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
#DEBHELPER#

exit 0
