FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1803 AS base

WORKDIR /app
COPY EmbyStat.Web/bin/Release/netcoreapp2.1/win7-x64/publish .

ENTRYPOINT ["dotnet", "EmbyStat.Web.dll", "--server.urls", "http://0.0.0.0:80"]
