env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'linebreak-style': ['error', 'windows'],
  'indent': ['error', 2],
  'semi': ['error', 'always'],
  'quotes': ['error', 'single'],
  'no-multi-spaces': ['error'],
  'no-console': 'warn',
  'no-duplicate-imports': 'warn',
  'max-len': ["error", { 
    code: 120, 
    ignoreComments: true,
    ignoreUrls: true,
    ignoreRegExpLiterals: true
  }],
  require-jsdoc: 0
}
