env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:jest-react/recommended
  - plugin:jsx-a11y/recommended
  - google
  - sonarqube
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - jest-react
  - '@typescript-eslint'
  - jsx-a11y
rules: {
  'react-hooks/exhaustive-deps': 'off',
  'react/jsx-no-useless-fragment': ['error', {'allowExpressions': true}],
  'react/jsx-boolean-value':'off',
  'jest/prefer-to-be-null': 'off',
  'jest/prefer-to-be-undefined': 'off',
  'prefer-arrow-callback': 'off',
  'linebreak-style': ['error', 'windows'],
  'indent': ['error', 2],
  'semi': ['error', 'always'],
  'quotes': ['error', 'single'],
  'no-multi-spaces': ['error'],
  'no-console': 'warn',
  'no-duplicate-imports': 'warn',
  'max-len': ["error", { 
    code: 120, 
    ignoreComments: true,
    ignoreUrls: true,
    ignoreRegExpLiterals: true
  }],
  require-jsdoc: 0
}
