jobs:
  - job: win_docker_publish
    displayName: 'Publish Windows docker images'
    steps:
      - template: publish.yml
        parameters:
          systemName: 'Windows'
          artifactName: 'EmbyStat-docker-$(package.win10-x64)-v$(Build.BuildNumber)'
          dockerFile: '../files/win.dockerfile'
          tag: 'beta-win-x64'
  - job: ubuntu_docker_publish
    displayName: 'Publish Ubuntu docker images'
    pool:
      vmImage: $(LinuxPool)
    steps:
      - template: publish.yml
        parameters:
          systemName: 'Ubuntu'
          artifactName: 'EmbyStat-docker-linux-v$(Build.BuildNumber)'
          dockerFile: '../files/linux.dockerfile'
          tag: 'beta-linux-x64'
  - job: arm64_docker_publish
    displayName: 'Publish ARM64 docker images'
    pool:
      vmImage: $(LinuxPool)
    steps:
      - template: publish.yml
        parameters:
          systemName: 'ARM64'
          artifactName: 'EmbyStat-docker-$(package.linux-arm-x64)-v$(Build.BuildNumber)'
          dockerFile: '../files/arm64.dockerfile'
          tag: 'beta-arm-x64'
  - job: arm_docker_publish
    displayName: 'Publish ARM docker images'
    pool:
      vmImage: $(LinuxPool)
    steps:
      - template: publish.yml
        parameters:
          systemName: 'ARM'
          artifactName: 'EmbyStat-docker-$(package.linux-arm)-v$(Build.BuildNumber)'
          dockerFile: '../files/arm.dockerfile'
          tag: 'beta-arm'
  - template: finish.yml
    parameters:
      dependsOn: [ ubuntu_docker_publish, win_docker_publish, arm64_docker_publish, arm_docker_publish ]
      manifestFile: '../files/manifest-beta.yaml'
      env: 'beta'

      