jobs:
- job: docker_container
  dependsOn: [win_docker_container, linux_docker_container, arm64_docker_container]
  condition: succeeded()
  displayName: 'Copy Docker files'
  variables:
    GitVersion.AssemblySemVer: $[ dependencies.main_build.outputs['setAssemblySemVer.AssemblySemVer'] ]
    GitVersion.SemVer: $[ dependencies.main_build.outputs['setSemVer.SemVer'] ]
  steps:
  - task: PowerShell@2
    displayName: 'Copy Docker files'
    inputs:
      targetType: filePath
      filePath: ./builds/docker-containers/dockerfiles.ps1

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Docker files'
    inputs:
      PathtoPublish: publish
      ArtifactName: 'EmbyStat-dockerfiles'