jobs:
- job: linux_docker_container
  displayName: 'Create Linux docker build'
  pool:
    vmImage: $(LinuxPool)
  variables:
    GitVersion.AssemblySemVer: $[stageDependencies.test_stage.main_build.outputs['setAssemblySemVer.AssemblySemVer'] ]
    GitVersion.SemVer: $[stageDependencies.test_stage.main_build.outputs['setSemVer.SemVer'] ]
  steps:
  - template: '../templates/update.version.yml'

  - task: PowerShell@2
    displayName: 'Update configuration'
    inputs:
      targetType: filePath
      filePath: $(paths.script)/appsettings.ps1
      arguments: '-updatePackage $(package.ubuntu-x64) -rollbarKey $(rollbar.key) -rollbarEnv $(rollbar.env) -version $(GitVersion.SemVer)'

  - task: DotNetCoreCLI@2
    displayName: 'Make linux-x64 package'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '$(webapp.project)'
      arguments: '-c Release -r linux-x64 -o publish -f $(publish.framework) $(publish.parameters)'
      zipAfterPublish: false
      modifyOutputPath: false
    
  - task: DotNetCoreCLI@2
    displayName: 'Make linux-x64 updater package'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '$(updater.project)'
      arguments: '-c Release -r linux-x64 -o publish/updater -f $(publish.framework) $(publish.parameters)'
      zipAfterPublish: false
      modifyOutputPath: false
      
  - template: '../templates/npmbuild.yml'
    parameters:
      npmBuild: 'run build -- --prod'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Linux Docker Artifact'
    inputs:
      PathtoPublish: 'publish'
      ArtifactName: 'EmbyStat-docker-linux-v$(Build.BuildNumber)'