using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EmbyStat.Migrations.Sqlite
{
    public partial class AddedAutoGeneratedId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_MediaPerson",
                table: "MediaPerson");

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "MediaPerson",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0)
                .Annotation("Sqlite:Autoincrement", true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_MediaPerson",
                table: "MediaPerson",
                column: "Id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_MediaPerson",
                table: "MediaPerson");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "MediaPerson");

            migrationBuilder.AddPrimaryKey(
                name: "PK_MediaPerson",
                table: "MediaPerson",
                columns: new[] { "ShowId", "MovieId", "EpisodeId", "PersonId", "Type" });
        }
    }
}
