// <auto-generated />
using System;
using EmbyStat.Core.DataStore;
using EmbyStat.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmbyStat.Migrations.Sqlite
{
    [DbContext(typeof(EsDbContext))]
    partial class EsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.EmbyStatUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("_refreshToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("RefreshTokens");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.FilterValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_Values")
                        .HasColumnType("TEXT")
                        .HasColumnName("Values");

                    b.HasKey("Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Genre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Helpers.MediaPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ShowId");

                    b.ToTable("MediaPerson");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentProgressPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78bc2bf0-abd9-48ef-aeff-9c396d644f2a"),
                            CurrentProgressPercentage = 0.0,
                            Description = "UPDATE-CHECKERDESCRIPTION",
                            State = 0,
                            Title = "UPDATE-CHECKER",
                            Trigger = "0 */12 * * *"
                        },
                        new
                        {
                            Id = new Guid("41e0bf22-1e6b-4f5d-90be-ec966f746a2f"),
                            CurrentProgressPercentage = 0.0,
                            Description = "SYSTEM-SYNCDESCRIPTION",
                            State = 0,
                            Title = "SYSTEM-SYNC",
                            Trigger = "0 2 * * *"
                        },
                        new
                        {
                            Id = new Guid("be68900b-ee1d-41ef-b12f-60ef3106052e"),
                            CurrentProgressPercentage = 0.0,
                            Description = "SHOW-SYNCDESCRIPTION",
                            State = 0,
                            Title = "SHOW-SYNC",
                            Trigger = "0 3 * * *"
                        },
                        new
                        {
                            Id = new Guid("ce1fbc9e-21ee-450b-9cdf-58a0e17ea98e"),
                            CurrentProgressPercentage = 0.0,
                            Description = "PINGDESCRIPTION",
                            State = 0,
                            Title = "PING",
                            Trigger = "*/5 * * * *"
                        },
                        new
                        {
                            Id = new Guid("b109ca73-0563-4062-a3e2-f7e6a00b73e9"),
                            CurrentProgressPercentage = 0.0,
                            Description = "DATABASE-CLEANUPDESCRIPTION",
                            State = 0,
                            Title = "DATABASE-CLEANUP",
                            Trigger = "0 4 * * *"
                        },
                        new
                        {
                            Id = new Guid("c40555dc-ea57-4c6e-a225-905223d31c3c"),
                            CurrentProgressPercentage = 0.0,
                            Description = "MOVIE-SYNCDESCRIPTION",
                            State = 0,
                            Title = "MOVIE-SYNC",
                            Trigger = "0 2 * * *"
                        });
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "e1940bfd-00c4-46f9-b9ac-a87a5d92e8ca",
                            Code = "da-DK",
                            Name = "Dansk"
                        },
                        new
                        {
                            Id = "c9df5e5c-75f3-46c2-8095-97fde33531d8",
                            Code = "de-DE",
                            Name = "Deutsch"
                        },
                        new
                        {
                            Id = "d6401f6b-becf-49e2-b82e-1018b3bf607f",
                            Code = "el-GR",
                            Name = "Ελληνικά"
                        },
                        new
                        {
                            Id = "62fe1b5e-3328-450b-b24b-fa16bea58870",
                            Code = "en-US",
                            Name = "English"
                        },
                        new
                        {
                            Id = "c0a60a3b-282e-46f5-aa7f-661c88f2edb0",
                            Code = "es-ES",
                            Name = "Español"
                        },
                        new
                        {
                            Id = "91cca672-af55-4d55-899a-798826a43773",
                            Code = "fi-FI",
                            Name = "Suomi"
                        },
                        new
                        {
                            Id = "99142c2f-379e-4a25-879b-ecfe25ee9e7c",
                            Code = "fr-FR",
                            Name = "Français"
                        },
                        new
                        {
                            Id = "a48a2ef9-3b64-4069-8e31-252abb6d07a3",
                            Code = "hu-HU",
                            Name = "Magyar"
                        },
                        new
                        {
                            Id = "282182b9-9332-4266-a093-5ff5b7f927a9",
                            Code = "it-IT",
                            Name = "Italiano"
                        },
                        new
                        {
                            Id = "082d8aaf-f86a-4401-bf0f-c315b3c9d904",
                            Code = "nl-NL",
                            Name = "Nederlands"
                        },
                        new
                        {
                            Id = "d8b0ae7b-9ba7-4a51-9d7c-94402b51265d",
                            Code = "no-NO",
                            Name = "Norsk"
                        },
                        new
                        {
                            Id = "f3966f43-3ec6-456e-850f-a2ebfc0b539b",
                            Code = "pl-PL",
                            Name = "Polski"
                        },
                        new
                        {
                            Id = "b21074db-74b9-4e24-8867-34e82c265256",
                            Code = "pt-BR",
                            Name = "Brasileiro"
                        },
                        new
                        {
                            Id = "490c1cb5-b711-4514-aa97-d22ddff2b2fa",
                            Code = "pt-PT",
                            Name = "Português"
                        },
                        new
                        {
                            Id = "6b103b14-20d1-49c0-b7ce-8d701399b64d",
                            Code = "ro-RO",
                            Name = "Românesc"
                        },
                        new
                        {
                            Id = "3e8d27e9-e314-4d57-967f-cf5d84144acf",
                            Code = "sv-SE",
                            Name = "Svenska"
                        },
                        new
                        {
                            Id = "97616a9b-60f9-407a-9a87-b4518da5e5f4",
                            Code = "zh-CN",
                            Name = "简体中文"
                        });
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Library", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSynced")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sync")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.MediaServerInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CachePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanLaunchWebBrowser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanSelfRestart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanSelfUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HardwareAccelerationRequiresPremiere")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPendingRestart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUpdateAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpServerPortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpsPortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalMetadataPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemsByNamePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystemDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramDataPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsAutoRunAtStartup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsHttps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLibraryMonitor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemUpdateLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscodingTempPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("WanAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("WebSocketPortNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MediaServerInfo");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.MediaServerStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MissedPings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MediaServerStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e55668a1-6a81-47ba-882d-738347e7e9cd"),
                            MissedPings = 0
                        });
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.MediaServerUserView", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "MediaId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("MediaServerUserViews");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Movies.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommunityRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("IMDB")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RunTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TMDB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TVDB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .HasColumnType("TEXT");

                    b.Property<int>("Video3DFormat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityRating");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Logo");

                    b.HasIndex("Name");

                    b.HasIndex("Primary");

                    b.HasIndex("RunTimeTicks");

                    b.HasIndex("SortName");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.PluginInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Episode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommunityRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<float?>("DvdEpisodeNumber")
                        .HasColumnType("REAL");

                    b.Property<int?>("DvdSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IMDB")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndexNumberEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RunTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TMDB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TVDB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .HasColumnType("TEXT");

                    b.Property<int>("Video3DFormat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Season", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndexNumberEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Show", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommunityRating")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CumulativeRunTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExternalSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IMDB")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RunTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SizeInMb")
                        .HasColumnType("REAL");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TMDB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TVDB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommunityRating");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Logo");

                    b.HasIndex("Name");

                    b.HasIndex("Primary");

                    b.HasIndex("RunTimeTicks");

                    b.HasIndex("SortName");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Statistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonResult")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.AudioStream", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelLayout")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("AudioStream");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.MediaSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Container")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RunTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SizeInMb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.HasIndex("SizeInMb");

                    b.ToTable("MediaSource");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.SubtitleStream", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("Language");

                    b.HasIndex("MovieId");

                    b.ToTable("SubtitleStream");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.VideoStream", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectRatio")
                        .HasColumnType("TEXT");

                    b.Property<float?>("AverageFrameRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoRange")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AverageFrameRate");

                    b.HasIndex("BitDepth");

                    b.HasIndex("Codec");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("Height");

                    b.HasIndex("MovieId");

                    b.HasIndex("VideoRange");

                    b.HasIndex("Width");

                    b.ToTable("VideoStream");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Users.MediaServerUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayMissingEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAllDevices")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableContentDeletion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableContentDownloading")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLiveTvAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableMediaConversion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePublicSharing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSubtitleDownloading")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSubtitleManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSyncTranscoding")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasConfiguredEasyPassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasConfiguredPassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPassword")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvalidLoginAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHiddenFromUnusedDevices")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHiddenRemotely")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlayDefaultAudioTrack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryImageTag")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemoteClientBitrateLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SimultaneousStreamLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubtitleLanguagePreference")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleMode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaServerUsers");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<string>("GenresId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoviesId")
                        .HasColumnType("TEXT");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("GenreShow", b =>
                {
                    b.Property<string>("GenresId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowsId")
                        .HasColumnType("TEXT");

                    b.HasKey("GenresId", "ShowsId");

                    b.HasIndex("ShowsId");

                    b.ToTable("GenreShow");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Helpers.MediaPerson", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Movies.Movie", "Movie")
                        .WithMany("People")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmbyStat.Common.Models.Entities.Person", "Person")
                        .WithMany("MediaPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Show", "Show")
                        .WithMany("People")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.MediaServerUserView", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Episode", null)
                        .WithMany("Views")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("EmbyStat.Common.Models.Entities.Movies.Movie", null)
                        .WithMany("Views")
                        .HasForeignKey("MovieId");

                    b.HasOne("EmbyStat.Common.Models.Entities.Users.MediaServerUser", "User")
                        .WithMany("Views")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Movies.Movie", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Library", "Library")
                        .WithMany("Movies")
                        .HasForeignKey("LibraryId");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Episode", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Season", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Show", "Show")
                        .WithMany("Seasons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Show", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Library", "Library")
                        .WithMany("Shows")
                        .HasForeignKey("LibraryId");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.AudioStream", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Episode", "Episode")
                        .WithMany("AudioStreams")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmbyStat.Common.Models.Entities.Movies.Movie", "Movie")
                        .WithMany("AudioStreams")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.MediaSource", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Episode", "Episode")
                        .WithMany("MediaSources")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmbyStat.Common.Models.Entities.Movies.Movie", "Movie")
                        .WithMany("MediaSources")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.SubtitleStream", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Episode", "Episode")
                        .WithMany("SubtitleStreams")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmbyStat.Common.Models.Entities.Movies.Movie", "Movie")
                        .WithMany("SubtitleStreams")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Streams.VideoStream", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Episode", "Episode")
                        .WithMany("VideoStreams")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmbyStat.Common.Models.Entities.Movies.Movie", "Movie")
                        .WithMany("VideoStreams")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmbyStat.Common.Models.Entities.Movies.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreShow", b =>
                {
                    b.HasOne("EmbyStat.Common.Models.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmbyStat.Common.Models.Entities.Shows.Show", null)
                        .WithMany()
                        .HasForeignKey("ShowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Library", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Movies.Movie", b =>
                {
                    b.Navigation("AudioStreams");

                    b.Navigation("MediaSources");

                    b.Navigation("People");

                    b.Navigation("SubtitleStreams");

                    b.Navigation("VideoStreams");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Person", b =>
                {
                    b.Navigation("MediaPeople");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Episode", b =>
                {
                    b.Navigation("AudioStreams");

                    b.Navigation("MediaSources");

                    b.Navigation("SubtitleStreams");

                    b.Navigation("VideoStreams");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Shows.Show", b =>
                {
                    b.Navigation("People");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("EmbyStat.Common.Models.Entities.Users.MediaServerUser", b =>
                {
                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
