using EmbyStat.Common;
using EmbyStat.Common.Enums.StatisticEnum;
using EmbyStat.Common.Models.Entities.Statistics;

namespace EmbyStat.Core.DataStore.Seeds;

public static class StatisticPageSeed
{
    public static readonly StatisticPage[] Pages =
    {
        new() {Id = Constants.StatisticPageIds.MoviePage, Name = "MENU.MOVIES"},
        new() {Id = Constants.StatisticPageIds.ShowPage, Name = "MENU.SHOWS"}
    };

    public static readonly StatisticCard[] Cards =
    {
        new(Constants.MovieStatisticsIds.MovieTotalCount, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalCount),
        new(Constants.MovieStatisticsIds.MovieTotalGenreCount, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalGenreCount),
        new(Constants.MovieStatisticsIds.MovieTotalPlayLength, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalPlayLength),
        new(Constants.MovieStatisticsIds.MovieTotalDiskSpaceUsage, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalDiskSpaceUsage),
        new(Constants.MovieStatisticsIds.MovieTotalWatchedCount, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalWatchedCount),
        new(Constants.MovieStatisticsIds.MovieTotalWatchedTime, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalWatchedTime),
        new(Constants.MovieStatisticsIds.MovieTotalActorCount, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalActorCount),
        new(Constants.MovieStatisticsIds.MovieTotalDirectorCount, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalDirectorCount),
        new(Constants.MovieStatisticsIds.MovieTotalWriterCount, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalWriterCount),
        new(Constants.MovieStatisticsIds.MovieTotalCurrentWatchingCount, StatisticType.Movie, StatisticCardType.Card, Statistic.MovieTotalCurrentWatchingCount),
        new(Constants.MovieStatisticsIds.MovieHighestRatedList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieHighestRatedList),
        new(Constants.MovieStatisticsIds.MovieLowestRatedList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieLowestRatedList),
        new(Constants.MovieStatisticsIds.MovieOldestPremieredList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieOldestPremieredList),
        new(Constants.MovieStatisticsIds.MovieNewestPremieredList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieNewestPremieredList),
        new(Constants.MovieStatisticsIds.MovieShortestList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieShortestList),
        new(Constants.MovieStatisticsIds.MovieLongestList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieLongestList),
        new(Constants.MovieStatisticsIds.MovieLatestAddedList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieLatestAddedList),
        new(Constants.MovieStatisticsIds.MovieMostWatchedList, StatisticType.Movie, StatisticCardType.TopCard, Statistic.MovieMostWatchedList),
        new(Constants.MovieStatisticsIds.MovieGenreChart, StatisticType.Movie, StatisticCardType.BarChart, Statistic.MovieGenreChart),
        new(Constants.MovieStatisticsIds.MovieRatingChart, StatisticType.Movie, StatisticCardType.BarChart, Statistic.MovieRatingChart),
        new(Constants.MovieStatisticsIds.MoviePremiereYearChart, StatisticType.Movie, StatisticCardType.BarChart, Statistic.MoviePremiereYearChart),
        new(Constants.MovieStatisticsIds.MovieOfficialRatingChart, StatisticType.Movie, StatisticCardType.BarChart, Statistic.MovieOfficialRatingChart),
        new(Constants.MovieStatisticsIds.MovieWatchedPerHourOfDayChart, StatisticType.Movie, StatisticCardType.ComplexChart, Statistic.MovieWatchedPerHourOfDayChart),
        new(Constants.MovieStatisticsIds.MovieWatchedPerDayOfWeekChart, StatisticType.Movie, StatisticCardType.ComplexChart, Statistic.MovieWatchedPerDayOfWeekChart),
        new(Constants.ShowStatisticsIds.ShowTotalCount, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalCount),
        new(Constants.ShowStatisticsIds.ShowTotalGenreCount, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalGenreCount),
        new(Constants.ShowStatisticsIds.ShowCompleteCollectedCount, StatisticType.Show, StatisticCardType.Card, Statistic.ShowCompleteCollectedCount),
        new(Constants.ShowStatisticsIds.ShowTotalEpisodesCount, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalEpisodesCount),
        new(Constants.ShowStatisticsIds.ShowTotalMissingEpisodeCount, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalMissingEpisodeCount),
        new(Constants.ShowStatisticsIds.ShowTotalPlayLength, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalPlayLength),
        new(Constants.ShowStatisticsIds.ShowTotalDiskSpaceUsage, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalDiskSpaceUsage),
        new(Constants.ShowStatisticsIds.ShowTotalWatchedEpisodeCount, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalWatchedEpisodeCount),
        new(Constants.ShowStatisticsIds.ShowTotalWatchedTime, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalWatchedTime),
        new(Constants.ShowStatisticsIds.ShowTotalActorCount, StatisticType.Show, StatisticCardType.Card, Statistic.ShowTotalActorCount),
        new(Constants.ShowStatisticsIds.ShowNewestPremieredList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowNewestPremieredList),
        new(Constants.ShowStatisticsIds.ShowOldestPremieredList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowOldestPremieredList),
        new(Constants.ShowStatisticsIds.ShowLatestAddedList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowLatestAddedList),
        new(Constants.ShowStatisticsIds.ShowHighestRatedList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowHighestRatedList),
        new(Constants.ShowStatisticsIds.ShowLowestRatedList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowLowestRatedList),
        new(Constants.ShowStatisticsIds.ShowWithMostEpisodesList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowWithMostEpisodesList),
        new(Constants.ShowStatisticsIds.ShowMostDiskUsageList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowMostDiskUsageList),
        new(Constants.ShowStatisticsIds.ShowMostWatchedList, StatisticType.Show, StatisticCardType.TopCard, Statistic.ShowMostWatchedList),
        new(Constants.ShowStatisticsIds.ShowGenreChart, StatisticType.Show, StatisticCardType.BarChart, Statistic.ShowGenreChart),
        new(Constants.ShowStatisticsIds.ShowRatingChart, StatisticType.Show, StatisticCardType.BarChart, Statistic.ShowRatingChart),
        new(Constants.ShowStatisticsIds.ShowPremiereYearChart, StatisticType.Show, StatisticCardType.BarChart, Statistic.ShowPremiereYearChart),
        new(Constants.ShowStatisticsIds.ShowCollectedRateChart, StatisticType.Show, StatisticCardType.BarChart, Statistic.ShowCollectedRateChart),
        new(Constants.ShowStatisticsIds.ShowOfficialRatingChart, StatisticType.Show, StatisticCardType.BarChart, Statistic.ShowOfficialRatingChart),
        new(Constants.ShowStatisticsIds.EpisodeWatchedPerHourOfDayChart, StatisticType.Show, StatisticCardType.ComplexChart, Statistic.EpisodeWatchedPerHourOfDayChart),
        new(Constants.ShowStatisticsIds.EpisodeWatchedPerDayOfWeekChart, StatisticType.Show, StatisticCardType.ComplexChart, Statistic.EpisodeWatchedPerDayOfWeekChart),
        new(Constants.ShowStatisticsIds.ShowStateChart, StatisticType.Show, StatisticCardType.PieChart, Statistic.ShowStateChart),
    };

    public static StatisticPageCard[] PageCards =
    {
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalCount, 0),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalGenreCount, 1),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalPlayLength, 2),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalDiskSpaceUsage, 3),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalWatchedCount, 4),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalWatchedTime, 5),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalActorCount, 6),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalDirectorCount, 7),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalWriterCount, 8),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieTotalCurrentWatchingCount, 9),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieHighestRatedList, 0),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieLowestRatedList, 1),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieOldestPremieredList, 2),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieNewestPremieredList, 3),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieShortestList, 4),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieLongestList, 5),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieLatestAddedList, 6),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieMostWatchedList, 7),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieGenreChart, 0),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieRatingChart, 1),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MoviePremiereYearChart, 2),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieOfficialRatingChart, 3),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieWatchedPerHourOfDayChart, 4),
        new(Constants.StatisticPageIds.MoviePage, Constants.MovieStatisticsIds.MovieWatchedPerDayOfWeekChart, 5),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalCount, 0),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalGenreCount, 1),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowCompleteCollectedCount, 2),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalEpisodesCount, 3),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalMissingEpisodeCount, 4),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalPlayLength, 5),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalDiskSpaceUsage, 6),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalWatchedEpisodeCount, 7),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalWatchedTime, 8),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowTotalActorCount, 9),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowNewestPremieredList, 0),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowOldestPremieredList, 1),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowLatestAddedList, 2),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowHighestRatedList, 3),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowLowestRatedList, 4),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowWithMostEpisodesList, 5),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowMostDiskUsageList, 6),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowMostWatchedList, 7),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowGenreChart, 0),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowRatingChart, 1),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowPremiereYearChart, 2),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowCollectedRateChart, 3),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowOfficialRatingChart, 4),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.EpisodeWatchedPerHourOfDayChart, 0),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.EpisodeWatchedPerDayOfWeekChart, 1),
        new(Constants.StatisticPageIds.ShowPage, Constants.ShowStatisticsIds.ShowStateChart, 0),

    };
}