jobs:
  - job: set_version
    displayName: Test application
    pool:
      name: Hosted Windows 2019 with VS2019
      demands: java
    steps:
    - task: GitVersion@5
      displayName: 'Set Version'
      inputs:
        runtime: 'core'
        preferBundledVersion: false
        configFilePath: 'GitVersion.yml'

    - task: PowerShell@2
      displayName: 'Update build number'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "##vso[build.updatebuildnumber]$(GitVersion.SemVer)"'

    - template: './templates/update.version.yml'
    - template: './templates/sonarcloud.start.yml'

    - task: PowerShell@2
      displayName: 'Update appsettings.json version'
      inputs:
        targetType: filePath
        filePath: $(Paths.Script)/appsettings.ps1
        arguments: '-updatePackage $(package.win10-x64) -rollbarKey $(rollbar.key) -version $(GitVersion.SemVer)'

    - task: DotNetCoreCLI@2
      displayName: 'Build web app'
      inputs:
        projects: '$(webapp.projects)'
      
    - template: ./templates/unit.tests.yml

    - template: './templates/sonarcloud.end.yml'

    - powershell: 'Write-Host "##vso[build.updatebuildnumber]$(GitVersion.SemVer)"'
      displayName: 'Update build number'
      
    - powershell: echo "##vso[task.setvariable variable=AssemblySemVer;isOutput=true]$(GitVersion.AssemblySemVer)"
      name: setAssemblySemVer
      displayName: 'Set AssemblySemVer variable'

    - powershell: echo "##vso[task.setvariable variable=SemVer;isOutput=true]$(GitVersion.SemVer)"
      name: setSemVer
      displayName: 'Set SemVer variable'

  - template: windows/build.pipeline.yml
  - template: win-x64/build.pipeline.yml