jobs:
  - job: set_version
    displayName: Test application
    pool:
      name: Hosted Windows 2019 with VS2019
      demands: java
    steps:
  - template: './templates/version.variables.yml'
  - template: './templates/update.version.yml'
  - template: './templates/sonarcloud.start.yml'

    - task: PowerShell@2
      displayName: 'Update appsettings.json version'
      inputs:
        targetType: filePath
        filePath: $(Paths.Script)/appsettings.ps1
        arguments: '-updatePackage $(package.win10-x64) -rollbarKey $(rollbar.key) -version $(GitVersion.SemVer)'

    - task: DotNetCoreCLI@2
      displayName: 'Build web app'
      inputs:
        projects: '$(webapp.projects)'
      
    - template: ./templates/unit.tests.yml
    - template: './templates/sonarcloud.end.yml'

  - template: windows/build.pipeline.yml
  - template: win-x64/build.pipeline.yml
  - template: ubuntu-x64/build.pipeline.yml