trigger:
- develop

pr:
  branches:
    include:
    - develop
    - release/*
    exclude:
    - dependabot/*
    
variables:
  - group: dev-build
  - group: packages
  - name: WinPool
    value: 'windows-2022'
  - name: LinuxPool
    value: 'ubuntu-20.04'

pool:
  vmImage: $(WinPool)

stages:
  - template: 'templates/test.stage.yml'

  - stage: build_artifacts
    dependsOn: test_stage
    condition: succeeded()
    displayName: 'Build artifacts'
    jobs:
    - template: './win-x64/build.pipeline.yml'

    - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - template: docker-containers/win.pipeline.yml
      - template: docker-containers/linux.pipeline.yml

  - stage: publish
    dependsOn: 
      - build_artifacts
      - test_stage
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
    displayName: 'Publish docker artifacts'
    jobs:
    - template: './docker-containers/publish/dev.publish.yml'