import uuid from 'react-uuid';

import { FilterDefinition } from '../models/filter';

const showFilters: FilterDefinition[] = [
  {
    field: "Name",
    label: "Title {0} {1}",
    title: "FILTERS.TITLES.TITLE",
    types: [
      {
        operation: "contains",
        label: "FILTERS.CONTAINS",
        type: "txt",
        open: false,
        id: uuid(),
        placeholder: "FILTERS.TITLES.TITLE",
      },
      {
        operation: "!contains",
        label: "FILTERS.NOTCONTAINS",
        type: "txt",
        open: false,
        id: uuid(),
        placeholder: "FILTERS.TITLES.TITLE",
      },
      {
        operation: "==",
        label: "FILTERS.EQUAL",
        type: "txt",
        open: false,
        id: uuid(),
        placeholder: "FILTERS.TITLES.TITLE",
      },
      {
        operation: "startsWith",
        label: "FILTERS.STARTSWITH",
        type: "txt",
        open: false,
        id: uuid(),
        placeholder: "FILTERS.TITLES.TITLE",
      },
      {
        operation: "endsWith",
        label: "FILTERS.ENDSWITH",
        type: "txt",
        open: false,
        id: uuid(),
        placeholder: "FILTERS.TITLES.TITLE",
      },
    ],
    open: false,
    id: uuid(),
  },
  {
    field: "IMDB",
    label: "Imdb {0} {1}",
    title: "FILTERS.TITLES.IMDB",
    types: [
      {
        operation: "==",
        label: "FILTERS.IS",
        type: "txt",
        open: false,
        id: uuid(),
        placeholder: "Imdb id",
      },
      {
        operation: "null",
        label: "FILTERS.ISNULL",
        type: "none",
        open: false,
        id: uuid(),
      },
    ],
    open: false,
    id: uuid(),
  },
  {
    field: "TMDB",
    label: "Tmdb {0} {1}",
    title: "FILTERS.TITLES.TMDB",
    types: [
      {
        operation: "==",
        label: "FILTERS.IS",
        type: "txt",
        open: false,
        id: uuid(),
        placeholder: "Tmdb id",
      },
      {
        operation: "null",
        label: "FILTERS.ISNULL",
        type: "none",
        open: false,
        id: uuid(),
      },
    ],
    open: false,
    id: uuid(),
  },
  {
    field: "Images",
    label: "Images {0} {1}",
    title: "FILTERS.TITLES.IMAGES",
    types: [
      {
        operation: "!null",
        label: "FILTERS.HAS",
        type: "dropdown",
        itemType: "static",
        items: [
          { label: "Primary", value: "Primary" },
          { label: "Logo", value: "Logo" },
        ],
        open: false,
        id: uuid(),
      },
      {
        operation: "null",
        label: "FILTERS.HASNO",
        type: "dropdown",
        itemType: "static",
        items: [
          { label: "Primary", value: "Primary" },
          { label: "Logo", value: "Logo" },
        ],
        open: false,
        id: uuid(),
      },
    ],
    open: false,
    id: uuid(),
  },
  {
    field: "Genres",
    label: "Genres {0} {1}",
    title: "COMMON.GENRES",
    types: [
      {
        operation: "any",
        label: "FILTERS.HAS",
        type: "dropdown",
        itemType: "url",
        itemUrl: "1/genre",
        open: false,
        id: uuid(),
      },
      {
        operation: "!any",
        label: "FILTERS.HASNO",
        type: "dropdown",
        itemType: "url",
        itemUrl: "1/genre",
        open: false,
        id: uuid(),
      },
    ],
    open: false,
    id: uuid(),
  },
  {
    field: "CommunityRating",
    label: "Community rating {0} {1}",
    title: "COMMON.COMMUNITYRATING",
    types: [
      {
        operation: "==",
        label: "FILTERS.IS",
        type: "number",
        unit: "",
        open: false,
        id: uuid(),
        placeholder: "COMMON.COMMUNITYRATING",
      },
      {
        operation: "between",
        label: "FILTERS.BETWEEN",
        type: "range",
        unit: "",
        min: 0,
        max: 10,
        step: 0.5,
        open: false,
        id: uuid(),
      },
    ],
    open: false,
    id: uuid(),
  },
  {
    field: "RunTimeTicks",
    label: "Runtime {0} {1}",
    title: "COMMON.RUNTIME",
    types: [
      {
        operation: "<",
        label: "FILTERS.SHORTER",
        type: "number",
        unit: "COMMON.MIN",
        open: false,
        id: uuid(),
      },
      {
        operation: ">",
        label: "FILTERS.LONGER",
        type: "number",
        unit: "COMMON.MIN",
        open: false,
        id: uuid(),
      },
      {
        operation: "between",
        label: "FILTERS.BETWEEN",
        type: "range",
        min: 0,
        max: 400,
        step: 20,
        unit: "COMMON.MIN",
        open: false,
        id: uuid(),
      },
      {
        operation: "null",
        label: "FILTERS.ISZERO",
        type: "none",
        open: false,
        id: uuid(),
      },
    ],
    open: false,
    id: uuid(),
  }
];

export default showFilters;
