jobs:
- job: fedora_x64
  displayName: 'Build Fedora x64 package'
  pool:
    vmImage: ubuntu-18.04
  variables:
    GitVersion.AssemblySemVer: $[stageDependencies.test_stage.main_build.outputs['setAssemblySemVer.AssemblySemVer'] ]
    GitVersion.SemVer: $[stageDependencies.test_stage.main_build.outputs['setSemVer.SemVer'] ]
  steps:
  - template: '../templates/update.version.yml'

  - task: PowerShell@2
    displayName: 'Update configuration'
    inputs:
      targetType: filePath
      filePath: $(paths.script)/appsettings.ps1
      arguments: '-updatePackage $(package.fedora-x64) -rollbarKey $(rollbar.key) -rollbarEnv $(rollbar.env) -version $(GitVersion.SemVer)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Make dotnet fedora-x64 package'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '$(webapp.project)'
      arguments: '-c Release -r fedora-x64 -o publish -f $(publish.framework) --self-contained true $(publish.parameters)'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: 'Make dotnet fedora-x64 updater package'
    inputs:
      command: publish
      publishWebProjects: false
      projects: '$(updater.project)'
      arguments: '-c Release -r fedora-x64 -o publish/updater -f $(publish.framework) --self-contained true $(publish.parameters)'
      zipAfterPublish: false
      modifyOutputPath: false
      
  - template: '../templates/npmbuild.yml'
    parameters:
      npmBuild: 'run build -- --prod'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Fedora x64 Artifact'
    inputs:
      PathtoPublish: 'publish'
      ArtifactName: 'EmbyStat-$(package.fedora-x64)-v$(GitVersion.SemVer)'